name: 'Algolia Docsearch Scraper'
description: 'Update the devportal-docs index on Algolia'
inputs:
  algolia_application_id:
    description: 'Algolia docsearch APPLICATION_ID'
    required: true
  algolia_api_key:
    description: 'Algolia docsearch API_KEY'
    required: true
  files:
    description: 'File paths to docsearch'
    required: true
  added:
    description: 'new files to index'
    required: false
  removed:
    description: 'files to remove records'
    required: false
  updated:
    description: 'files to update records'
    required: false
  renamed:
    description: 'files to update records'
    required: false
outputs:
  errors:
    description: >
      Array of urls with errors
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.algolia_application_id }}
    - ${{ inputs.algolia_api_key }}
    - ${{ inputs.file }}
    - ${{ inputs.added }}
    - ${{ inputs.removed }}
    - ${{ inputs.updated }}
    - ${{ inputs.renamed }}
